### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/maahad-eng#2]
@Alir3z4 how is it done exactly? is it Angular side or PHP side?

**Comment by Alir3z4** [comment]
The main domain ?
You can do that with .htaccess to force redirect from http to https.
I've the similar thing in gonevis dash code

**Comment by AmirSavand** [comment]
@Alir3z4 ok I will try, but how does it work for `localhost`?

**Comment by Alir3z4** [comment]
In localhost I'm sure ` .htaccess` will be respected by the local web-server.
