### ISSUE TITLE
Upgrade to PrestaShop 1.7

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/maahad-eng#3]
https://www.prestashop.com/en/download

**Comment by Alir3z4** [comment]
We're already on 1.7.2

**Comment by Alir3z4** [comment]
where did you get a notification for this ?

**Comment by AmirSavand** [comment]
@Alir3z4 from email, I think it's yesterdays update, if we're latest then close the issue.

But check the version form their website.

**Comment by AmirSavand** [comment]
@Alir3z4 If it's done, close it.
